### ISSUE TITLE
Custom datasets with non-local file paths produce invalid pipelines

### ISSUE THREAD

**Issue by marrrcin** [getindata/kedro-kubeflow#123]
If you create custom dataset for Kedro (implement `AbstractDataSet`) with the following specification:
* use `filepath` as an argument
* use fsspec-compatible, non-local path as value of `filepath` argument, e.g. `s3://...` or `gs://...`

the compiled pipeline yaml will contain invalid output specification, making the pipeline fail in Kubeflow at runtime with:

> This step is in Error state with this message: failed to save outputs: stat /home/kedro/s3://my-bucket-name123/tmp/models/model_checkpoint.pth: no such file or directory

`catalog.yml`
```yaml
model_checkpoint:
  type: myproject.datasets.ModelCheckpoint
  filepath: s3://my-bucket-name123/tmp/models/model_checkpoint.pth
```

`pipeline.yml` fragment:
```yaml
outputs:
      artifacts:
      - {name: train-model-node-model_checkpoint, path: '/home/kedro/s3://my-bucket-name123/tmp/models/model_checkpoint.pth'}
```

This happens because of the logic in the generator https://github.com/getindata/kedro-kubeflow/blob/be5f0b1f35462baf0d3f9041bc87f2a3cc6a7c9a/kedro_kubeflow/generators/pod_per_node_pipeline_generator.py#L134-L141
