### ISSUE TITLE
Change default resource limits to something more reasonable

### ISSUE THREAD

**Issue by Lasica** [getindata/kedro-kubeflow#163]
Currently the default limit is:
```
  resources:
  (...)
    __default__:
      cpu: 200m
      memory: 64Mi
```
Which makes the starter spaceflights run fail. Let's change it to something more usable
