### ISSUE TITLE
Kedro to Kubeflow pipeline iris AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by cpereir1** [getindata/kedro-kubeflow#211]
Hi, I am trying to turn the kedro [iris sample project](https://kedro.readthedocs.io/en/stable/get_started/new_project.html) into a kubeflow pipelines deployment.

I have the following in place:
1) Local installation of kedro and successful execution of the iris project
2) Cloud deployment of kubeflow (with pipelines) to which I want to push the kedro-iris project
3) The kedro project containerized and available at a remote container registry following the instructions [here](https://kedro-kubeflow.readthedocs.io/en/0.7.3/source/03_getting_started/01_quickstart.html#install-the-toy-project-with-kubeflow-pipelines-support). All steps seem to work fine until:

Running **kedro kubeflow upload-pipeline** which gives me the following error:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/homebrew/bin/kedro:8 in <module>                                                            │
│                                                                                                  │
│   5 from kedro.framework.cli import main                                                         │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/kedro/framework/cli/cli.py:211 in main                │
│                                                                                                  │
│   208 │   """                                                                                    │
│   209 │   _init_plugins()                                                                        │
│   210 │   cli_collection = KedroCLI(project_path=Path.cwd())                                     │
│ ❱ 211 │   cli_collection()                                                                       │
│   212                                                                                            │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/core.py:1130 in __call__                        │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/kedro/framework/cli/cli.py:139 in main                │
│                                                                                                  │
│   136 │   │   )                                                                                  │
│   137 │   │                                                                                      │
│   138 │   │   try:                                                                               │
│ ❱ 139 │   │   │   super().main(                                                                  │
│   140 │   │   │   │   args=args,                                                                 │
│   141 │   │   │   │   prog_name=prog_name,                                                       │
│   142 │   │   │   │   complete_var=complete_var,                                                 │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/core.py:1055 in main                            │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/core.py:1657 in invoke                          │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/core.py:1657 in invoke                          │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/core.py:1404 in invoke                          │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/core.py:760 in invoke                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/click/decorators.py:26 in new_func                    │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/kedro_kubeflow/cli.py:200 in upload_pipeline          │
│                                                                                                  │
│   197 │   context_helper = ctx.obj["context_helper"]                                             │
│   198 │   config = context_helper.config.run_config                                              │
│   199 │                                                                                          │
│ ❱ 200 │   context_helper.kfp_client.upload(                                                      │
│   201 │   │   pipeline_name=pipeline,                                                            │
│   202 │   │   image=image if image else config.image,                                            │
│   203 │   │   image_pull_policy=config.image_pull_policy,                                        │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/kedro_kubeflow/kfpclient.py:112 in upload             │
│                                                                                                  │
│   109 │   │   │   version_id = self._upload_pipeline_version(pipeline, pipeline_id)              │
│   110 │   │   │   self.log.info("New version of pipeline created: %s", version_id)               │
│   111 │   │   else:                                                                              │
│ ❱ 112 │   │   │   (pipeline_id, version_id) = self._upload_pipeline(                             │
│   113 │   │   │   │   pipeline, full_pipeline_name                                               │
│   114 │   │   │   )                                                                              │
│   115 │   │   │   self.log.info("Pipeline created")                                              │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/kedro_kubeflow/kfpclient.py:146 in _upload_pipeline   │
│                                                                                                  │
│   143 │   │   │   │   description=self.pipeline_description,                                     │
│   144 │   │   │   │   _request_timeout=10000,                                                    │
│   145 │   │   │   )                                                                              │
│ ❱ 146 │   │   │   return (pipeline.id, pipeline.default_version.id)                              │
│   147 │                                                                                          │
│   148 │   def _ensure_experiment_exists(self, experiment_name, experiment_namespace):            │
│   149 │   │   try: 

AttributeError: 'NoneType' object has no attribute 'id'
```

This is my kubeflow.yaml:

```
host: https://<host>/pipelines/?ns=<namespace>
run_config:
  image: <image_in_remote_container_url>
  image_pull_policy: Always #IfNotPresent
  experiment_name: test-experiment
  run_name: iris-test-run
  scheduled_run_name: 
  description: "Test kedro2kubeflow iris training pipeline"
  wait_for_completion: False
  ttl: 604800
  store_kedro_outputs_as_kfp_artifacts: False
  volume:
    storageclass:
    size: 1Gi
    access_modes: [ReadWriteMany]
    skip_init: False
    owner: 0
    keep: False
  resources:
    split_data:
      memory: 1Gi
    make_predictions:
      cpu: 1
      memory: 1Gi
    report_accuracy:
      cpu: 0.5
      memory: 1Gi

    __default__:
      cpu: 1
      memory: 1Gi

  retry_policy:
    wait_for_partition_availability:
      num_retries: 90
      backoff_duration: 5m
      backoff_factor: 1

    __default__:
      num_retries: 4
      backoff_duration: 60s
      backoff_factor: 2

  tolerations:
    __default__:
    - key: "dedicated"
      operator: "Equal"
      value: "ml-ops"
      effect: "NoSchedule"
```

What could I be doing wrong?

Local Kedro version: 0.18.4

Thank you!
