### ISSUE TITLE
Starter spaceflights isn't working with kind: auth and pipeline fail

### ISSUE THREAD

**Issue by prise6** [getindata/kedro-kubeflow#275]
Is the starter with local kubenertes (kind) still working like [Quickstart] documentation assume ?

## Issues

1. when using `kedro kubeflow upload-pipeline` i can't sign in, i managed to make it work by manually forcing `KubeflowClient` to have following cookies keys: oauth2_proxy_kubeflow, auth, token. Values were copied from my browser. I think `obtain_dex_authservice_session()` method is not working anymore ?  It seems that form scraping for Dex is not up to date (but maybe i did something wrong)

2. when launching generated pipeline in kubeflow ui, `data-volume-create` don't create a volume and output log are : `This step output is taken from cache.`. So next step `data-volume-init` fails. When i set `skip_init: True`, first step is working but next steps of course fail because data is not copied.
I don't know very well kube (or kind) to debug to be honest. Is someone can confirm that documentation is up to date and spaceflights is working with kind/dex ? Thank you.

## Local config

Here's some of my configurations:

* kedro version: 0.19.8
* kedro-kubeflow>=0.8.0
* kedro-docker>=0.6.2
* kind: 0.27.0

I'm using the start kit with `catalog.yml` :

<details>

<summary>catalog.yml</summary>

```yml
companies:
  type: pandas.CSVDataset
  filepath: data/01_raw/companies.csv

reviews:
  type: pandas.CSVDataset
  filepath: data/01_raw/reviews.csv

shuttles:
  type: pandas.ExcelDataset
  filepath: data/01_raw/shuttles.xlsx
  load_args:
    engine: openpyxl

preprocessed_companies:
  type: pandas.ParquetDataset
  filepath: data/02_intermediate/preprocessed_companies.parquet

preprocessed_shuttles:
  type: pandas.ParquetDataset
  filepath: data/02_intermediate/preprocessed_shuttles.parquet

model_input_table:
  type: pandas.ParquetDataset
  filepath: data/03_primary/model_input_table.parquet

regressor:
  type: pickle.PickleDataset
  filepath: data/06_models/regressor.pickle
  versioned: true

shuttle_passenger_capacity_plot_exp:
  type: plotly.PlotlyDataset
  filepath: data/08_reporting/shuttle_passenger_capacity_plot_exp.json
  versioned: true
  plotly_args:
    type: bar
    fig:
      x: shuttle_type
      y: passenger_capacity
      orientation: h
    layout:
      xaxis_title: Shuttles
      yaxis_title: Average passenger capacity
      title: Shuttle Passenger capacity

shuttle_passenger_capacity_plot_go:
  type: plotly.JSONDataset
  filepath: data/08_reporting/shuttle_passenger_capacity_plot_go.json
  versioned: true

dummy_confusion_matrix:
  type: matplotlib.MatplotlibWriter
  filepath: data/08_reporting/dummy_confusion_matrix.png
  versioned: true
``` 

</details>

Generated `kubeflow.yml`

<details>

<summary>pipeline.yml</summary>

```yml

# Base url of the Kubeflow Pipelines, should include the schema (http/https)
host: <host>

# Configuration used to run the pipeline
run_config:

  # Name of the image to run as the pipeline steps
  image: <img>:debug

  # Pull policy to be used for the steps. Use Always if you push the images
  # on the same tag, or Never if you use only local images
  image_pull_policy: IfNotPresent

  # Name of the kubeflow experiment to be created
  experiment_name: kedro-mlops-demo

  # Name of the run for run-once, templated with the run-once parameters
  run_name: kedro-mlops-demo

  # Name of the scheduled run, templated with the schedule parameters
  scheduled_run_name: kedro-mlops-demo

  # Optional pipeline description
  #description: "Very Important Pipeline"

  # Flag indicating if the run-once should wait for the pipeline to finish
  wait_for_completion: False

  # How long to keep underlying Argo workflow (together with pods and data
  # volume after pipeline finishes) [in seconds]. Default: 1 week
  ttl: 604800

  # What Kedro pipeline should be run as the last step regardless of the
  # pipeline status. Used to send notifications or raise the alerts
  # on_exit_pipeline: notify_via_slack

  # This sets the caching option for pipeline using
  # execution_options.caching_strategy.max_cache_staleness
  # See https://en.wikipedia.org/wiki/ISO_8601 in section 'Duration'
  # max_cache_staleness: P0D

  # Set to false to disable kfp artifacts exposal
  # This setting can be useful if you don't want to store
  # intermediate results in the MLMD
  # store_kedro_outputs_as_kfp_artifacts: True

  # Strategy used to generate Kubeflow pipeline nodes from Kedro nodes
  # Available strategies:
  #  * none (default) - nodes in Kedro pipeline are mapped to separate nodes
  #                     in Kubeflow pipelines. This strategy allows to inspect
  #                     a whole processing graph in Kubeflow UI and override
  #                     resources for each node (because they are run in separate pods)
  #                     Although, performance may not be optimal due to potential
  #                     sharing of intermediate datasets through disk.
  #  * full - nodes in Kedro pipeline are mapped to one node in Kubeflow pipelines.
  #           This strategy mitigate potential performance issues with `none` strategy
  #           but at the cost of degraded user experience within Kubeflow UI: a graph
  #           is collapsed to one node.
  # node_merge_strategy: none

  # Optional volume specification
  volume:

    # Storage class - use null (or no value) to use the default storage
    # class deployed on the Kubernetes cluster
    storageclass: null # default

    # The size of the volume that is created. Applicable for some storage
    # classes
    size: 1Gi

    # Access mode of the volume used to exchange data. ReadWriteMany is
    # preferred, but it is not supported on some environements (like GKE)
    # Default value: ReadWriteOnce
    # access_modes: [ReadWriteMany]

    # Flag indicating if the data-volume-init step (copying raw data to the
    # fresh volume) should be skipped
    skip_init: False

    # Allows to specify user executing pipelines within containers
    # Default: root user (to avoid issues with volumes in GKE)
    owner: 0

    # Flak indicating if volume for inter-node data exchange should be
    # kept after the pipeline is deleted
    keep: False

  # Optional section allowing adjustment of the resources
  # reservations and limits for the nodes
  resources:

    # For nodes that require more RAM you can increase the "memory"
    data_import_step:
      memory: 2Gi

    # Training nodes can utilize more than one CPU if the algoritm
    # supports it
    model_training:
      cpu: 8
      memory: 1Gi

    # GPU-capable nodes can request 1 GPU slot
    tensorflow_step:
      nvidia.com/gpu: 1

    # Default settings for the nodes
    __default__:
      cpu: 1
      memory: 1Gi

  # Optional section to allow mounting additional volumes (such as EmptyDir)
  # to specific nodes
  extra_volumes:
    tensorflow_step:
    - mount_path: /dev/shm
      volume:
        name: shared_memory
        empty_dir:
          cls: V1EmptyDirVolumeSource
          params:
            medium: Memory

  # Optional section to provide retry policy for the steps
  # and default policy for steps with no policy specified
  retry_policy:
    # 90 retries every 5 minutes
    wait_for_partition_availability:
      num_retries: 90
      backoff_duration: 5m
      backoff_factor: 1

    # 4 retries after: 1 minute, 2 minutes, 4 minutes, 8 minutes
    __default__:
      num_retries: 4
      backoff_duration: 60s
      backoff_factor: 2
    # Optional section allowing adjustment of the resources
  # reservations and limits for the nodes
  # optional section for specifying tolerations per node.
  # the __default__ section will be loaded if nothing is specified for a particular node.
  tolerations:
    __default__:
    - key: "dedicated"
      operator: "Equal"
      value: "ml-ops"
      effect: "NoSchedule"
    node_a:
    - key: "gpu_resource"
      operator: "Equal"
      value: "voltaire"
      effect: "NoSchedule"

```

</details>

Generated pipeline

<details>

<summary>pipeline.yml</summary>

```yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kedro-mlops-demo-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-05-01T02:42:40.240153',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Convert from a Kedro pipeline
      into a kfp container graph.", "inputs": [{"default": "{\"features\": [\"engines\",
      \"passenger_capacity\", \"crew\", \"d_check_complete\", \"moon_clearance_complete\",
      \"iata_approved\", \"company_rating\", \"review_scores_rating\"], \"random_state\":
      3, \"test_size\": 0.2}", "name": "model_options", "optional": true}], "name":
      "kedro_mlops_demo"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: kedro-mlops-demo
  templates:
  - name: compare-passenger-capacity-exp-preprocessed-shuttles-shuttle-passenger-capacity-plot-exp
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          compare_passenger_capacity_exp([preprocessed_shuttles]) -> [shuttle_passenger_capacity_plot_exp]
          --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: compare-passenger-capacity-exp-preprocessed-shuttles-shuttle-passenger-capacity-plot-exp-shuttle_passenger_capacity_plot_exp,
        path: /home/kedro/data/08_reporting/shuttle_passenger_capacity_plot_exp.json}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: compare-passenger-capacity-go-preprocessed-shuttles-shuttle-passenger-capacity-plot-go
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          compare_passenger_capacity_go([preprocessed_shuttles]) -> [shuttle_passenger_capacity_plot_go]
          --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: compare-passenger-capacity-go-preprocessed-shuttles-shuttle-passenger-capacity-plot-go-shuttle_passenger_capacity_plot_go,
        path: /home/kedro/data/08_reporting/shuttle_passenger_capacity_plot_go.json}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: create-confusion-matrix-companies-dummy-confusion-matrix
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          create_confusion_matrix([companies]) -> [dummy_confusion_matrix] --config
          config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: create-confusion-matrix-companies-dummy-confusion-matrix-dummy_confusion_matrix,
        path: /home/kedro/data/08_reporting/dummy_confusion_matrix.png}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: create-model-input-table-node
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          create_model_input_table_node --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: create-model-input-table-node-model_input_table, path: /home/kedro/data/03_primary/model_input_table.parquet}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: data-volume-create
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-default-data-volume'
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    outputs:
      parameters:
      - name: data-volume-create-manifest
        valueFrom: {jsonPath: '{}'}
      - name: data-volume-create-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: data-volume-create-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "false"
  - name: data-volume-init
    container:
      args: [cp --verbose -r /home/kedro/data/* /home/kedro/datavolume]
      command: [sh, -c]
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/datavolume, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: evaluate-model-node
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          evaluate_model_node --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: exit-handler-1
    inputs:
      parameters:
      - {name: model_options}
    dag:
      tasks:
      - name: compare-passenger-capacity-exp-preprocessed-shuttles-shuttle-passenger-capacity-plot-exp
        template: compare-passenger-capacity-exp-preprocessed-shuttles-shuttle-passenger-capacity-plot-exp
        dependencies: [data-volume-create, data-volume-init, preprocess-shuttles-node]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: compare-passenger-capacity-go-preprocessed-shuttles-shuttle-passenger-capacity-plot-go
        template: compare-passenger-capacity-go-preprocessed-shuttles-shuttle-passenger-capacity-plot-go
        dependencies: [data-volume-create, data-volume-init, preprocess-shuttles-node]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: create-confusion-matrix-companies-dummy-confusion-matrix
        template: create-confusion-matrix-companies-dummy-confusion-matrix
        dependencies: [data-volume-create, data-volume-init]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: create-model-input-table-node
        template: create-model-input-table-node
        dependencies: [data-volume-create, data-volume-init, preprocess-companies-node,
          preprocess-shuttles-node]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - {name: data-volume-create, template: data-volume-create}
      - name: data-volume-init
        template: data-volume-init
        dependencies: [data-volume-create]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
      - name: evaluate-model-node
        template: evaluate-model-node
        dependencies: [data-volume-create, data-volume-init, split-data-node, train-model-node]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: preprocess-companies-node
        template: preprocess-companies-node
        dependencies: [data-volume-create, data-volume-init]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: preprocess-shuttles-node
        template: preprocess-shuttles-node
        dependencies: [data-volume-create, data-volume-init]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: split-data-node
        template: split-data-node
        dependencies: [create-model-input-table-node, data-volume-create, data-volume-init]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
      - name: train-model-node
        template: train-model-node
        dependencies: [data-volume-create, data-volume-init, split-data-node]
        arguments:
          parameters:
          - {name: data-volume-create-name, value: '{{tasks.data-volume-create.outputs.parameters.data-volume-create-name}}'}
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
  - name: kedro-mlops-demo
    inputs:
      parameters:
      - {name: model_options}
    dag:
      tasks:
      - name: exit-handler-1
        template: exit-handler-1
        arguments:
          parameters:
          - {name: model_options, value: '{{inputs.parameters.model_options}}'}
  - name: on-exit
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}', status, '{{workflow.status}}',
        failures, '{{workflow.failures}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro kubeflow delete-pipeline-volume {{workflow.name}}-default-data-volume']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
    inputs:
      parameters:
      - {name: model_options}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
  - name: preprocess-companies-node
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          preprocess_companies_node --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: preprocess-companies-node-preprocessed_companies, path: /home/kedro/data/02_intermediate/preprocessed_companies.parquet}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: preprocess-shuttles-node
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          preprocess_shuttles_node --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: preprocess-shuttles-node-preprocessed_shuttles, path: /home/kedro/data/02_intermediate/preprocessed_shuttles.parquet}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: split-data-node
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          split_data_node --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  - name: train-model-node
    container:
      args: [_, model_options, '{{inputs.parameters.model_options}}']
      command: [bash, -c, 'python -c ''import yaml, sys;load=lambda e: yaml.load(e,
          Loader=yaml.FullLoader);params=dict(zip(sys.argv[1::2], [load(e) for e in
          sys.argv[2::2]]));f=open("config.yaml", "w");yaml.dump({"run": {"params":
          params}}, f)'' "$@" &&kedro run --env local --pipeline __default__ --nodes
          train_model_node --config config.yaml']
      env:
      - {name: IAP_CLIENT_ID, value: ''}
      - {name: KUBEFLOW_RUN_ID, value: '{{workflow.uid}}'}
      image: kedro-mlops-demo:demo
      imagePullPolicy: IfNotPresent
      resources:
        limits: {cpu: 1, memory: 1Gi}
        requests: {cpu: 1, memory: 1Gi}
      securityContext: {runAsUser: 0}
      volumeMounts:
      - {mountPath: /home/kedro/data, name: data-volume-create}
    inputs:
      parameters:
      - {name: data-volume-create-name}
      - {name: model_options}
    outputs:
      artifacts:
      - {name: train-model-node-regressor, path: /home/kedro/data/06_models/regressor.pickle}
    tolerations:
    - {effect: NoSchedule, key: dedicated, operator: Equal, value: ml-ops}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    retryStrategy:
      limit: 4
      retryPolicy: Always
      backoff: {duration: 60s, factor: 2}
    volumes:
    - name: data-volume-create
      persistentVolumeClaim: {claimName: '{{inputs.parameters.data-volume-create-name}}'}
  arguments:
    parameters:
    - {name: model_options, value: '{"features": ["engines", "passenger_capacity",
        "crew", "d_check_complete", "moon_clearance_complete", "iata_approved", "company_rating",
        "review_scores_rating"], "random_state": 3, "test_size": 0.2}'}
  serviceAccountName: pipeline-runner
  ttlStrategy: {secondsAfterCompletion: 604800}
  onExit: on-exit

``` 

</details>
